'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider, App } from 'antd';
import AntdThemeConfig from "@/config/theme.config";
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import { store, persistor } from '@/store';

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children
}: React.PropsWithChildren) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider theme={AntdThemeConfig}>
          <App>
            <AntdRegistry>
              <Provider store={store}>
                <PersistGate loading={null} persistor={persistor}>
                  {children}
                </PersistGate>
              </Provider>
            </AntdRegistry>
          </App>
        </ConfigProvider>
      </body>
    </html>
  );
}
