import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider, App } from 'antd';
import AntdThemeConfig from "@/config/theme.config";

import GlobalProvider from '@/components/GlobalProvider';

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: React.PropsWithChildren) {
  console.log('RootLayout 只运行一次');
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider theme={AntdThemeConfig}>
          <App>
            <GlobalProvider />
            <AntdRegistry>
              {children}
            </AntdRegistry>
          </App>
        </ConfigProvider>
      </body>
    </html>
  );
}
